---
resources:
- name: yjeong-blog-git
  type: git
  source:
    uri: https://github.com/younjinjeong/yjeong.cfapps.io/
- name: yjeong-pipelines-git
  type: git
  source:
    uri: https://github.com/younjinjeong/pipelines/
- name: yjeong-blog-staging
  type: cf
  source: 
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}} 
    space: {{cf-space}} 
    skip_cert_check: {{skip_cert_check}}

jobs:
- name: yjeong-blog-test-app
  public: true
  serial: true
  plan:
  - get: yjeong-blog-git
    trigger: true
  - get: yjeong-pipelines-git
    trigger: true
  - task: yjeong-blog-test
    file: yjeong-pipelines-git/blog/yjeong-blog-test.yml
  - put: yjeong-blog-staging
    params:
      path: yjeong-blog-git/public/
      manifest: yjeong-pipelines-git/blog/yjeong_blog_manifest.yml
